// Copyright 2026 Joshua Winkler and The yolocam Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/ai_capture.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This fires when the AI Parameter section's Start button is pressed (phase=3) and again at
// the end of the flow (phase=1).
//
// The camera always answers status 100 (not implemented). Yololiv Compose seems to implement
// the AI feature entirely client-side, grabbing a frame (property 100/raw_frame_cache),
// analyzing it locally, and writing back ordinary exposure/white-balance SETs.
type AiParameterStartStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1     uint32                 `protobuf:"varint,1,opt,name=unknown_1,json=unknown1,proto3" json:"unknown_1,omitempty"` // constant 3
	Phase         uint32                 `protobuf:"varint,2,opt,name=phase,proto3" json:"phase,omitempty"`                       // 3 = start, 1 = stop
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiParameterStartStop) Reset() {
	*x = AiParameterStartStop{}
	mi := &file_yolocam_v1_ai_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiParameterStartStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiParameterStartStop) ProtoMessage() {}

func (x *AiParameterStartStop) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_ai_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiParameterStartStop.ProtoReflect.Descriptor instead.
func (*AiParameterStartStop) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_ai_capture_proto_rawDescGZIP(), []int{0}
}

func (x *AiParameterStartStop) GetUnknown_1() uint32 {
	if x != nil {
		return x.Unknown_1
	}
	return 0
}

func (x *AiParameterStartStop) GetPhase() uint32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

// A processed still frame the camera caches to its own filesystem for the Color page's custom
// color-swatch picker to sample from. byte_size is exactly width*height*1.5 (YUV420/NV12).
type StillFrameCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByteSize      uint32                 `protobuf:"varint,1,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"` // "/app_data/cache/<id>.yuv"
	Width         uint32                 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StillFrameCache) Reset() {
	*x = StillFrameCache{}
	mi := &file_yolocam_v1_ai_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StillFrameCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StillFrameCache) ProtoMessage() {}

func (x *StillFrameCache) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_ai_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StillFrameCache.ProtoReflect.Descriptor instead.
func (*StillFrameCache) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_ai_capture_proto_rawDescGZIP(), []int{1}
}

func (x *StillFrameCache) GetByteSize() uint32 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *StillFrameCache) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StillFrameCache) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StillFrameCache) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Same cached-file shape as StillFrameCache but a .raw sensor grab rather than a processed still
// used by the AiParameterStartStop functionality.
//
// shutter_us matches the shutter value in effect at capture time.
type RawFrameCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByteSize      uint32                 `protobuf:"varint,1,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // "/app_data/cache/<id>.raw"
	ShutterUs     uint32                 `protobuf:"varint,3,opt,name=shutter_us,json=shutterUs,proto3" json:"shutter_us,omitempty"`
	Unknown_4     uint32                 `protobuf:"varint,4,opt,name=unknown_4,json=unknown4,proto3" json:"unknown_4,omitempty"`
	Unknown_5     uint32                 `protobuf:"varint,5,opt,name=unknown_5,json=unknown5,proto3" json:"unknown_5,omitempty"`
	Unknown_6     uint32                 `protobuf:"varint,6,opt,name=unknown_6,json=unknown6,proto3" json:"unknown_6,omitempty"`
	Unknown_7     uint32                 `protobuf:"varint,7,opt,name=unknown_7,json=unknown7,proto3" json:"unknown_7,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFrameCache) Reset() {
	*x = RawFrameCache{}
	mi := &file_yolocam_v1_ai_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFrameCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFrameCache) ProtoMessage() {}

func (x *RawFrameCache) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_ai_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFrameCache.ProtoReflect.Descriptor instead.
func (*RawFrameCache) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_ai_capture_proto_rawDescGZIP(), []int{2}
}

func (x *RawFrameCache) GetByteSize() uint32 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *RawFrameCache) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RawFrameCache) GetShutterUs() uint32 {
	if x != nil {
		return x.ShutterUs
	}
	return 0
}

func (x *RawFrameCache) GetUnknown_4() uint32 {
	if x != nil {
		return x.Unknown_4
	}
	return 0
}

func (x *RawFrameCache) GetUnknown_5() uint32 {
	if x != nil {
		return x.Unknown_5
	}
	return 0
}

func (x *RawFrameCache) GetUnknown_6() uint32 {
	if x != nil {
		return x.Unknown_6
	}
	return 0
}

func (x *RawFrameCache) GetUnknown_7() uint32 {
	if x != nil {
		return x.Unknown_7
	}
	return 0
}

var File_yolocam_v1_ai_capture_proto protoreflect.FileDescriptor

const file_yolocam_v1_ai_capture_proto_rawDesc = "" +
	"\n" +
	"\x1byolocam/v1/ai_capture.proto\x12\n" +
	"yolocam.v1\"I\n" +
	"\x14AiParameterStartStop\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\rR\x05phase\"p\n" +
	"\x0fStillFrameCache\x12\x1b\n" +
	"\tbyte_size\x18\x01 \x01(\rR\bbyteSize\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05width\x18\x05 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\rR\x06height\"\xd3\x01\n" +
	"\rRawFrameCache\x12\x1b\n" +
	"\tbyte_size\x18\x01 \x01(\rR\bbyteSize\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"shutter_us\x18\x03 \x01(\rR\tshutterUs\x12\x1b\n" +
	"\tunknown_4\x18\x04 \x01(\rR\bunknown4\x12\x1b\n" +
	"\tunknown_5\x18\x05 \x01(\rR\bunknown5\x12\x1b\n" +
	"\tunknown_6\x18\x06 \x01(\rR\bunknown6\x12\x1b\n" +
	"\tunknown_7\x18\a \x01(\rR\bunknown7B\xab\x01\n" +
	"\x0ecom.yolocam.v1B\x0eAiCaptureProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_ai_capture_proto_rawDescOnce sync.Once
	file_yolocam_v1_ai_capture_proto_rawDescData []byte
)

func file_yolocam_v1_ai_capture_proto_rawDescGZIP() []byte {
	file_yolocam_v1_ai_capture_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_ai_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_ai_capture_proto_rawDesc), len(file_yolocam_v1_ai_capture_proto_rawDesc)))
	})
	return file_yolocam_v1_ai_capture_proto_rawDescData
}

var file_yolocam_v1_ai_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yolocam_v1_ai_capture_proto_goTypes = []any{
	(*AiParameterStartStop)(nil), // 0: yolocam.v1.AiParameterStartStop
	(*StillFrameCache)(nil),      // 1: yolocam.v1.StillFrameCache
	(*RawFrameCache)(nil),        // 2: yolocam.v1.RawFrameCache
}
var file_yolocam_v1_ai_capture_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolocam_v1_ai_capture_proto_init() }
func file_yolocam_v1_ai_capture_proto_init() {
	if File_yolocam_v1_ai_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_ai_capture_proto_rawDesc), len(file_yolocam_v1_ai_capture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_ai_capture_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_ai_capture_proto_depIdxs,
		MessageInfos:      file_yolocam_v1_ai_capture_proto_msgTypes,
	}.Build()
	File_yolocam_v1_ai_capture_proto = out.File
	file_yolocam_v1_ai_capture_proto_goTypes = nil
	file_yolocam_v1_ai_capture_proto_depIdxs = nil
}
