// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/color.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// styles_json is a fixed catalog of every built-in style option, including each one's
// lutFileUrl on Yololiv's own Aliyun OSS bucket. It is not the current selection, so don't read
// a selected styleId out of it.
//
// lut_byte_size matches ScenProfilePack.size_or_id exactly. Both are the LUT byte size.
type ColorStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StyleId       uint32                 `protobuf:"varint,1,opt,name=style_id,json=styleId,proto3" json:"style_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Unknown_4     uint32                 `protobuf:"varint,4,opt,name=unknown_4,json=unknown4,proto3" json:"unknown_4,omitempty"`
	LutByteSize   uint32                 `protobuf:"varint,5,opt,name=lut_byte_size,json=lutByteSize,proto3" json:"lut_byte_size,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Unknown_7     uint32                 `protobuf:"varint,7,opt,name=unknown_7,json=unknown7,proto3" json:"unknown_7,omitempty"`
	StylesJson    string                 `protobuf:"bytes,8,opt,name=styles_json,json=stylesJson,proto3" json:"styles_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorStyle) Reset() {
	*x = ColorStyle{}
	mi := &file_yolocam_v1_color_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorStyle) ProtoMessage() {}

func (x *ColorStyle) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_color_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorStyle.ProtoReflect.Descriptor instead.
func (*ColorStyle) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_color_proto_rawDescGZIP(), []int{0}
}

func (x *ColorStyle) GetStyleId() uint32 {
	if x != nil {
		return x.StyleId
	}
	return 0
}

func (x *ColorStyle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ColorStyle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ColorStyle) GetUnknown_4() uint32 {
	if x != nil {
		return x.Unknown_4
	}
	return 0
}

func (x *ColorStyle) GetLutByteSize() uint32 {
	if x != nil {
		return x.LutByteSize
	}
	return 0
}

func (x *ColorStyle) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ColorStyle) GetUnknown_7() uint32 {
	if x != nil {
		return x.Unknown_7
	}
	return 0
}

func (x *ColorStyle) GetStylesJson() string {
	if x != nil {
		return x.StylesJson
	}
	return ""
}

// Fires alongside every color_style (50) change.
//
// gzip_blob is a gzip-compressed POSIX tar archive (~389KB decompressed) containing the
// AE/AWB/WDR ISP scene tuning for the style (config_scenemode.ini, scene_4k25_linear_0.ini), a
// manifest, and LUT data also carried by property 95 (clut_data_binary_baseline).
//
// Built-in styles are exposure/white-balance presets: only the tuning ini and a metadata file
// differ between styles; every LUT-shaped file is byte-identical across all of them.
//
// size_or_id matches ColorStyle.lut_byte_size for the same change.
type ScenProfilePack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1     uint32                 `protobuf:"varint,1,opt,name=unknown_1,json=unknown1,proto3" json:"unknown_1,omitempty"` // constant 1
	Unknown_2     uint32                 `protobuf:"varint,2,opt,name=unknown_2,json=unknown2,proto3" json:"unknown_2,omitempty"` // constant 1
	SizeOrId      uint32                 `protobuf:"varint,3,opt,name=size_or_id,json=sizeOrId,proto3" json:"size_or_id,omitempty"`
	GzipBlob      []byte                 `protobuf:"bytes,4,opt,name=gzip_blob,json=gzipBlob,proto3" json:"gzip_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenProfilePack) Reset() {
	*x = ScenProfilePack{}
	mi := &file_yolocam_v1_color_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenProfilePack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenProfilePack) ProtoMessage() {}

func (x *ScenProfilePack) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_color_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenProfilePack.ProtoReflect.Descriptor instead.
func (*ScenProfilePack) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_color_proto_rawDescGZIP(), []int{1}
}

func (x *ScenProfilePack) GetUnknown_1() uint32 {
	if x != nil {
		return x.Unknown_1
	}
	return 0
}

func (x *ScenProfilePack) GetUnknown_2() uint32 {
	if x != nil {
		return x.Unknown_2
	}
	return 0
}

func (x *ScenProfilePack) GetSizeOrId() uint32 {
	if x != nil {
		return x.SizeOrId
	}
	return 0
}

func (x *ScenProfilePack) GetGzipBlob() []byte {
	if x != nil {
		return x.GzipBlob
	}
	return nil
}

// Fires alongside every color_style (50) change, twice per change: first a sparse zero-keyed
// placeholder, then the real dense blob.
//
// clut_size is constant (5508) across every observation and matches the `clutSize` field of the
// LUT JSON bundled in property 52's tar.
//
// clut_data is byte-identical across every built-in style tested; a fixed shared baseline, not
// a per-style grade. Its exact internal encoding is not decoded.
type ClutDataBinaryBaseline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClutSize      uint32                 `protobuf:"varint,1,opt,name=clut_size,json=clutSize,proto3" json:"clut_size,omitempty"`
	ClutData      []byte                 `protobuf:"bytes,2,opt,name=clut_data,json=clutData,proto3" json:"clut_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClutDataBinaryBaseline) Reset() {
	*x = ClutDataBinaryBaseline{}
	mi := &file_yolocam_v1_color_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClutDataBinaryBaseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClutDataBinaryBaseline) ProtoMessage() {}

func (x *ClutDataBinaryBaseline) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_color_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClutDataBinaryBaseline.ProtoReflect.Descriptor instead.
func (*ClutDataBinaryBaseline) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_color_proto_rawDescGZIP(), []int{2}
}

func (x *ClutDataBinaryBaseline) GetClutSize() uint32 {
	if x != nil {
		return x.ClutSize
	}
	return 0
}

func (x *ClutDataBinaryBaseline) GetClutData() []byte {
	if x != nil {
		return x.ClutData
	}
	return nil
}

// Each value is a string holding a plain int (not a numeric field), range -100..100, default
// "0".
type Hsl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HueRed        string                 `protobuf:"bytes,1,opt,name=hue_red,json=hueRed,proto3" json:"hue_red,omitempty"`
	HueOrange     string                 `protobuf:"bytes,2,opt,name=hue_orange,json=hueOrange,proto3" json:"hue_orange,omitempty"`
	HueYellow     string                 `protobuf:"bytes,3,opt,name=hue_yellow,json=hueYellow,proto3" json:"hue_yellow,omitempty"`
	HueGreen      string                 `protobuf:"bytes,4,opt,name=hue_green,json=hueGreen,proto3" json:"hue_green,omitempty"`
	HueCyan       string                 `protobuf:"bytes,5,opt,name=hue_cyan,json=hueCyan,proto3" json:"hue_cyan,omitempty"`
	HueBlue       string                 `protobuf:"bytes,6,opt,name=hue_blue,json=hueBlue,proto3" json:"hue_blue,omitempty"`
	HuePurple     string                 `protobuf:"bytes,7,opt,name=hue_purple,json=huePurple,proto3" json:"hue_purple,omitempty"`
	HueMagenta    string                 `protobuf:"bytes,8,opt,name=hue_magenta,json=hueMagenta,proto3" json:"hue_magenta,omitempty"`
	SatRed        string                 `protobuf:"bytes,9,opt,name=sat_red,json=satRed,proto3" json:"sat_red,omitempty"`
	SatOrange     string                 `protobuf:"bytes,10,opt,name=sat_orange,json=satOrange,proto3" json:"sat_orange,omitempty"`
	SatYellow     string                 `protobuf:"bytes,11,opt,name=sat_yellow,json=satYellow,proto3" json:"sat_yellow,omitempty"`
	SatGreen      string                 `protobuf:"bytes,12,opt,name=sat_green,json=satGreen,proto3" json:"sat_green,omitempty"`
	SatCyan       string                 `protobuf:"bytes,13,opt,name=sat_cyan,json=satCyan,proto3" json:"sat_cyan,omitempty"`
	SatBlue       string                 `protobuf:"bytes,14,opt,name=sat_blue,json=satBlue,proto3" json:"sat_blue,omitempty"`
	SatPurple     string                 `protobuf:"bytes,15,opt,name=sat_purple,json=satPurple,proto3" json:"sat_purple,omitempty"`
	SatMagenta    string                 `protobuf:"bytes,16,opt,name=sat_magenta,json=satMagenta,proto3" json:"sat_magenta,omitempty"`
	LightRed      string                 `protobuf:"bytes,17,opt,name=light_red,json=lightRed,proto3" json:"light_red,omitempty"`
	LightOrange   string                 `protobuf:"bytes,18,opt,name=light_orange,json=lightOrange,proto3" json:"light_orange,omitempty"`
	LightYellow   string                 `protobuf:"bytes,19,opt,name=light_yellow,json=lightYellow,proto3" json:"light_yellow,omitempty"`
	LightGreen    string                 `protobuf:"bytes,20,opt,name=light_green,json=lightGreen,proto3" json:"light_green,omitempty"`
	LightCyan     string                 `protobuf:"bytes,21,opt,name=light_cyan,json=lightCyan,proto3" json:"light_cyan,omitempty"`
	LightBlue     string                 `protobuf:"bytes,22,opt,name=light_blue,json=lightBlue,proto3" json:"light_blue,omitempty"`
	LightPurple   string                 `protobuf:"bytes,23,opt,name=light_purple,json=lightPurple,proto3" json:"light_purple,omitempty"`
	LightMagenta  string                 `protobuf:"bytes,24,opt,name=light_magenta,json=lightMagenta,proto3" json:"light_magenta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hsl) Reset() {
	*x = Hsl{}
	mi := &file_yolocam_v1_color_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hsl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hsl) ProtoMessage() {}

func (x *Hsl) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_color_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hsl.ProtoReflect.Descriptor instead.
func (*Hsl) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_color_proto_rawDescGZIP(), []int{3}
}

func (x *Hsl) GetHueRed() string {
	if x != nil {
		return x.HueRed
	}
	return ""
}

func (x *Hsl) GetHueOrange() string {
	if x != nil {
		return x.HueOrange
	}
	return ""
}

func (x *Hsl) GetHueYellow() string {
	if x != nil {
		return x.HueYellow
	}
	return ""
}

func (x *Hsl) GetHueGreen() string {
	if x != nil {
		return x.HueGreen
	}
	return ""
}

func (x *Hsl) GetHueCyan() string {
	if x != nil {
		return x.HueCyan
	}
	return ""
}

func (x *Hsl) GetHueBlue() string {
	if x != nil {
		return x.HueBlue
	}
	return ""
}

func (x *Hsl) GetHuePurple() string {
	if x != nil {
		return x.HuePurple
	}
	return ""
}

func (x *Hsl) GetHueMagenta() string {
	if x != nil {
		return x.HueMagenta
	}
	return ""
}

func (x *Hsl) GetSatRed() string {
	if x != nil {
		return x.SatRed
	}
	return ""
}

func (x *Hsl) GetSatOrange() string {
	if x != nil {
		return x.SatOrange
	}
	return ""
}

func (x *Hsl) GetSatYellow() string {
	if x != nil {
		return x.SatYellow
	}
	return ""
}

func (x *Hsl) GetSatGreen() string {
	if x != nil {
		return x.SatGreen
	}
	return ""
}

func (x *Hsl) GetSatCyan() string {
	if x != nil {
		return x.SatCyan
	}
	return ""
}

func (x *Hsl) GetSatBlue() string {
	if x != nil {
		return x.SatBlue
	}
	return ""
}

func (x *Hsl) GetSatPurple() string {
	if x != nil {
		return x.SatPurple
	}
	return ""
}

func (x *Hsl) GetSatMagenta() string {
	if x != nil {
		return x.SatMagenta
	}
	return ""
}

func (x *Hsl) GetLightRed() string {
	if x != nil {
		return x.LightRed
	}
	return ""
}

func (x *Hsl) GetLightOrange() string {
	if x != nil {
		return x.LightOrange
	}
	return ""
}

func (x *Hsl) GetLightYellow() string {
	if x != nil {
		return x.LightYellow
	}
	return ""
}

func (x *Hsl) GetLightGreen() string {
	if x != nil {
		return x.LightGreen
	}
	return ""
}

func (x *Hsl) GetLightCyan() string {
	if x != nil {
		return x.LightCyan
	}
	return ""
}

func (x *Hsl) GetLightBlue() string {
	if x != nil {
		return x.LightBlue
	}
	return ""
}

func (x *Hsl) GetLightPurple() string {
	if x != nil {
		return x.LightPurple
	}
	return ""
}

func (x *Hsl) GetLightMagenta() string {
	if x != nil {
		return x.LightMagenta
	}
	return ""
}

var File_yolocam_v1_color_proto protoreflect.FileDescriptor

const file_yolocam_v1_color_proto_rawDesc = "" +
	"\n" +
	"\x16yolocam/v1/color.proto\x12\n" +
	"yolocam.v1\"\xfe\x01\n" +
	"\n" +
	"ColorStyle\x12\x19\n" +
	"\bstyle_id\x18\x01 \x01(\rR\astyleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tunknown_4\x18\x04 \x01(\rR\bunknown4\x12\"\n" +
	"\rlut_byte_size\x18\x05 \x01(\rR\vlutByteSize\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12\x1b\n" +
	"\tunknown_7\x18\a \x01(\rR\bunknown7\x12\x1f\n" +
	"\vstyles_json\x18\b \x01(\tR\n" +
	"stylesJson\"\x86\x01\n" +
	"\x0fScenProfilePack\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\x12\x1b\n" +
	"\tunknown_2\x18\x02 \x01(\rR\bunknown2\x12\x1c\n" +
	"\n" +
	"size_or_id\x18\x03 \x01(\rR\bsizeOrId\x12\x1b\n" +
	"\tgzip_blob\x18\x04 \x01(\fR\bgzipBlob\"R\n" +
	"\x16ClutDataBinaryBaseline\x12\x1b\n" +
	"\tclut_size\x18\x01 \x01(\rR\bclutSize\x12\x1b\n" +
	"\tclut_data\x18\x02 \x01(\fR\bclutData\"\xe3\x05\n" +
	"\x03Hsl\x12\x17\n" +
	"\ahue_red\x18\x01 \x01(\tR\x06hueRed\x12\x1d\n" +
	"\n" +
	"hue_orange\x18\x02 \x01(\tR\thueOrange\x12\x1d\n" +
	"\n" +
	"hue_yellow\x18\x03 \x01(\tR\thueYellow\x12\x1b\n" +
	"\thue_green\x18\x04 \x01(\tR\bhueGreen\x12\x19\n" +
	"\bhue_cyan\x18\x05 \x01(\tR\ahueCyan\x12\x19\n" +
	"\bhue_blue\x18\x06 \x01(\tR\ahueBlue\x12\x1d\n" +
	"\n" +
	"hue_purple\x18\a \x01(\tR\thuePurple\x12\x1f\n" +
	"\vhue_magenta\x18\b \x01(\tR\n" +
	"hueMagenta\x12\x17\n" +
	"\asat_red\x18\t \x01(\tR\x06satRed\x12\x1d\n" +
	"\n" +
	"sat_orange\x18\n" +
	" \x01(\tR\tsatOrange\x12\x1d\n" +
	"\n" +
	"sat_yellow\x18\v \x01(\tR\tsatYellow\x12\x1b\n" +
	"\tsat_green\x18\f \x01(\tR\bsatGreen\x12\x19\n" +
	"\bsat_cyan\x18\r \x01(\tR\asatCyan\x12\x19\n" +
	"\bsat_blue\x18\x0e \x01(\tR\asatBlue\x12\x1d\n" +
	"\n" +
	"sat_purple\x18\x0f \x01(\tR\tsatPurple\x12\x1f\n" +
	"\vsat_magenta\x18\x10 \x01(\tR\n" +
	"satMagenta\x12\x1b\n" +
	"\tlight_red\x18\x11 \x01(\tR\blightRed\x12!\n" +
	"\flight_orange\x18\x12 \x01(\tR\vlightOrange\x12!\n" +
	"\flight_yellow\x18\x13 \x01(\tR\vlightYellow\x12\x1f\n" +
	"\vlight_green\x18\x14 \x01(\tR\n" +
	"lightGreen\x12\x1d\n" +
	"\n" +
	"light_cyan\x18\x15 \x01(\tR\tlightCyan\x12\x1d\n" +
	"\n" +
	"light_blue\x18\x16 \x01(\tR\tlightBlue\x12!\n" +
	"\flight_purple\x18\x17 \x01(\tR\vlightPurple\x12#\n" +
	"\rlight_magenta\x18\x18 \x01(\tR\flightMagentaB\xa7\x01\n" +
	"\x0ecom.yolocam.v1B\n" +
	"ColorProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_color_proto_rawDescOnce sync.Once
	file_yolocam_v1_color_proto_rawDescData []byte
)

func file_yolocam_v1_color_proto_rawDescGZIP() []byte {
	file_yolocam_v1_color_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_color_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_color_proto_rawDesc), len(file_yolocam_v1_color_proto_rawDesc)))
	})
	return file_yolocam_v1_color_proto_rawDescData
}

var file_yolocam_v1_color_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yolocam_v1_color_proto_goTypes = []any{
	(*ColorStyle)(nil),             // 0: yolocam.v1.ColorStyle
	(*ScenProfilePack)(nil),        // 1: yolocam.v1.ScenProfilePack
	(*ClutDataBinaryBaseline)(nil), // 2: yolocam.v1.ClutDataBinaryBaseline
	(*Hsl)(nil),                    // 3: yolocam.v1.Hsl
}
var file_yolocam_v1_color_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolocam_v1_color_proto_init() }
func file_yolocam_v1_color_proto_init() {
	if File_yolocam_v1_color_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_color_proto_rawDesc), len(file_yolocam_v1_color_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_color_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_color_proto_depIdxs,
		MessageInfos:      file_yolocam_v1_color_proto_msgTypes,
	}.Build()
	File_yolocam_v1_color_proto = out.File
	file_yolocam_v1_color_proto_goTypes = nil
	file_yolocam_v1_color_proto_depIdxs = nil
}
