// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/device.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelFirmware string                 `protobuf:"bytes,1,opt,name=model_firmware,json=modelFirmware,proto3" json:"model_firmware,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Build         string                 `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_yolocam_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetModelFirmware() string {
	if x != nil {
		return x.ModelFirmware
	}
	return ""
}

func (x *DeviceInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceInfo) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

var File_yolocam_v1_device_proto protoreflect.FileDescriptor

const file_yolocam_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x17yolocam/v1/device.proto\x12\n" +
	"yolocam.v1\"a\n" +
	"\n" +
	"DeviceInfo\x12%\n" +
	"\x0emodel_firmware\x18\x01 \x01(\tR\rmodelFirmware\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x14\n" +
	"\x05build\x18\x04 \x01(\tR\x05buildB\xa8\x01\n" +
	"\x0ecom.yolocam.v1B\vDeviceProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_device_proto_rawDescOnce sync.Once
	file_yolocam_v1_device_proto_rawDescData []byte
)

func file_yolocam_v1_device_proto_rawDescGZIP() []byte {
	file_yolocam_v1_device_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_device_proto_rawDesc), len(file_yolocam_v1_device_proto_rawDesc)))
	})
	return file_yolocam_v1_device_proto_rawDescData
}

var file_yolocam_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yolocam_v1_device_proto_goTypes = []any{
	(*DeviceInfo)(nil), // 0: yolocam.v1.DeviceInfo
}
var file_yolocam_v1_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolocam_v1_device_proto_init() }
func file_yolocam_v1_device_proto_init() {
	if File_yolocam_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_device_proto_rawDesc), len(file_yolocam_v1_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_device_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_device_proto_depIdxs,
		MessageInfos:      file_yolocam_v1_device_proto_msgTypes,
	}.Build()
	File_yolocam_v1_device_proto = out.File
	file_yolocam_v1_device_proto_goTypes = nil
	file_yolocam_v1_device_proto_depIdxs = nil
}
