// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/envelope.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_GET         MessageType = 1
	MessageType_MESSAGE_TYPE_SET         MessageType = 2
	MessageType_MESSAGE_TYPE_REPLY       MessageType = 4
	MessageType_MESSAGE_TYPE_PUSH        MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_GET",
		2: "MESSAGE_TYPE_SET",
		4: "MESSAGE_TYPE_REPLY",
		5: "MESSAGE_TYPE_PUSH",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_GET":         1,
		"MESSAGE_TYPE_SET":         2,
		"MESSAGE_TYPE_REPLY":       4,
		"MESSAGE_TYPE_PUSH":        5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_yolocam_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_yolocam_v1_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_yolocam_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// A Message is the protobuf payload of one framed TCP packet. Framing wraps it in a 14-byte
// header and 2-byte trailer that are not protobuf, so a client has to parse them by hand before
// this message ever comes into view.
//
//	outer header, 8 bytes:
//	+--------+--------+--------+--------+--------------------------+
//	| 0x08   | dir    | 0x00   | 0x00   | rest_len (uint32, LE)    |
//	+--------+--------+--------+--------+--------------------------+
//
//	inner header, 6 bytes:
//	+--------+-----------------------------------+-----------------+
//	| 0xA5   | payload_len (uint32, BE)          | hdr_xor         |
//	+--------+-----------------------------------+-----------------+
//
//	payload, payload_len bytes:
//	+-----------------------------------------------------------------+
//	| protobuf payload                                                 |
//	+-----------------------------------------------------------------+
//
//	trailer, 2 bytes:
//	+--------+--------+
//	| pl_xor | 0x5A   |
//	+--------+--------+
//
// dir is 0x01 for app to camera, 0x00 for camera to app.
//
// rest_len counts every byte after the outer header: 6 + payload_len + 2. payload_len itself is
// big-endian, unlike rest_len; that mismatch is the only reason this framing ever looked opaque.
//
// hdr_xor is the XOR of the five preceding inner-header bytes (0xA5 and the four length bytes).
// pl_xor is the XOR of every payload byte. 0x5A is a fixed terminator (0xA5 with its nibbles
// swapped).
//
// Frames are pipelined and can share TCP segments, so read the stream and walk it by rest_len
// rather than assuming one frame per read.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=yolocam.v1.MessageType" json:"type,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Status        uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Property      PropertyId             `protobuf:"varint,5,opt,name=property,proto3,enum=yolocam.v1.PropertyId" json:"property,omitempty"`
	Value         *Value                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_yolocam_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Message) GetProperty() PropertyId {
	if x != nil {
		return x.Property
	}
	return PropertyId_PROPERTY_ID_UNSPECIFIED
}

func (x *Message) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_IntValue
	//	*Value_StringValue_2
	//	*Value_StringValue_7
	//	*Value_DeviceInfo
	//	*Value_WbRedBlueOffset
	//	*Value_Rect
	//	*Value_ColorStyle
	//	*Value_IntWrapper
	//	*Value_RectList
	//	*Value_StringWrapper
	//	*Value_SceneProfilePack
	//	*Value_Empty
	//	*Value_AiParameterStartStop
	//	*Value_RawFrameCache
	//	*Value_ClutDataBinaryBaseline
	//	*Value_StillFrameCache
	//	*Value_FrameRateStatus
	//	*Value_ZoomRect
	//	*Value_Hsl
	//	*Value_KeyedZoomTable
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_yolocam_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetStringValue_2() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue_2); ok {
			return x.StringValue_2
		}
	}
	return ""
}

func (x *Value) GetStringValue_7() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue_7); ok {
			return x.StringValue_7
		}
	}
	return ""
}

func (x *Value) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		if x, ok := x.Kind.(*Value_DeviceInfo); ok {
			return x.DeviceInfo
		}
	}
	return nil
}

func (x *Value) GetWbRedBlueOffset() *RedBlueOffset {
	if x != nil {
		if x, ok := x.Kind.(*Value_WbRedBlueOffset); ok {
			return x.WbRedBlueOffset
		}
	}
	return nil
}

func (x *Value) GetRect() *Rect {
	if x != nil {
		if x, ok := x.Kind.(*Value_Rect); ok {
			return x.Rect
		}
	}
	return nil
}

func (x *Value) GetColorStyle() *ColorStyle {
	if x != nil {
		if x, ok := x.Kind.(*Value_ColorStyle); ok {
			return x.ColorStyle
		}
	}
	return nil
}

func (x *Value) GetIntWrapper() *IntWrapper {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntWrapper); ok {
			return x.IntWrapper
		}
	}
	return nil
}

func (x *Value) GetRectList() *RectList {
	if x != nil {
		if x, ok := x.Kind.(*Value_RectList); ok {
			return x.RectList
		}
	}
	return nil
}

func (x *Value) GetStringWrapper() *StringWrapper {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringWrapper); ok {
			return x.StringWrapper
		}
	}
	return nil
}

func (x *Value) GetSceneProfilePack() *ScenProfilePack {
	if x != nil {
		if x, ok := x.Kind.(*Value_SceneProfilePack); ok {
			return x.SceneProfilePack
		}
	}
	return nil
}

func (x *Value) GetEmpty() *Empty {
	if x != nil {
		if x, ok := x.Kind.(*Value_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *Value) GetAiParameterStartStop() *AiParameterStartStop {
	if x != nil {
		if x, ok := x.Kind.(*Value_AiParameterStartStop); ok {
			return x.AiParameterStartStop
		}
	}
	return nil
}

func (x *Value) GetRawFrameCache() *RawFrameCache {
	if x != nil {
		if x, ok := x.Kind.(*Value_RawFrameCache); ok {
			return x.RawFrameCache
		}
	}
	return nil
}

func (x *Value) GetClutDataBinaryBaseline() *ClutDataBinaryBaseline {
	if x != nil {
		if x, ok := x.Kind.(*Value_ClutDataBinaryBaseline); ok {
			return x.ClutDataBinaryBaseline
		}
	}
	return nil
}

func (x *Value) GetStillFrameCache() *StillFrameCache {
	if x != nil {
		if x, ok := x.Kind.(*Value_StillFrameCache); ok {
			return x.StillFrameCache
		}
	}
	return nil
}

func (x *Value) GetFrameRateStatus() *FrameRateStatus {
	if x != nil {
		if x, ok := x.Kind.(*Value_FrameRateStatus); ok {
			return x.FrameRateStatus
		}
	}
	return nil
}

func (x *Value) GetZoomRect() *ZoomRect {
	if x != nil {
		if x, ok := x.Kind.(*Value_ZoomRect); ok {
			return x.ZoomRect
		}
	}
	return nil
}

func (x *Value) GetHsl() *Hsl {
	if x != nil {
		if x, ok := x.Kind.(*Value_Hsl); ok {
			return x.Hsl
		}
	}
	return nil
}

func (x *Value) GetKeyedZoomTable() *KeyedZoomTable {
	if x != nil {
		if x, ok := x.Kind.(*Value_KeyedZoomTable); ok {
			return x.KeyedZoomTable
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_StringValue_2 struct {
	StringValue_2 string `protobuf:"bytes,2,opt,name=string_value_2,json=stringValue2,proto3,oneof"`
}

type Value_StringValue_7 struct {
	StringValue_7 string `protobuf:"bytes,7,opt,name=string_value_7,json=stringValue7,proto3,oneof"`
}

type Value_DeviceInfo struct {
	DeviceInfo *DeviceInfo `protobuf:"bytes,10,opt,name=device_info,json=deviceInfo,proto3,oneof"`
}

type Value_WbRedBlueOffset struct {
	WbRedBlueOffset *RedBlueOffset `protobuf:"bytes,13,opt,name=wb_red_blue_offset,json=wbRedBlueOffset,proto3,oneof"`
}

type Value_Rect struct {
	Rect *Rect `protobuf:"bytes,14,opt,name=rect,proto3,oneof"`
}

type Value_ColorStyle struct {
	ColorStyle *ColorStyle `protobuf:"bytes,16,opt,name=color_style,json=colorStyle,proto3,oneof"`
}

type Value_IntWrapper struct {
	IntWrapper *IntWrapper `protobuf:"bytes,17,opt,name=int_wrapper,json=intWrapper,proto3,oneof"`
}

type Value_RectList struct {
	RectList *RectList `protobuf:"bytes,19,opt,name=rect_list,json=rectList,proto3,oneof"`
}

type Value_StringWrapper struct {
	StringWrapper *StringWrapper `protobuf:"bytes,22,opt,name=string_wrapper,json=stringWrapper,proto3,oneof"`
}

type Value_SceneProfilePack struct {
	SceneProfilePack *ScenProfilePack `protobuf:"bytes,5,opt,name=scene_profile_pack,json=sceneProfilePack,proto3,oneof"`
}

type Value_Empty struct {
	Empty *Empty `protobuf:"bytes,28,opt,name=empty,proto3,oneof"`
}

type Value_AiParameterStartStop struct {
	AiParameterStartStop *AiParameterStartStop `protobuf:"bytes,29,opt,name=ai_parameter_start_stop,json=aiParameterStartStop,proto3,oneof"`
}

type Value_RawFrameCache struct {
	RawFrameCache *RawFrameCache `protobuf:"bytes,30,opt,name=raw_frame_cache,json=rawFrameCache,proto3,oneof"`
}

type Value_ClutDataBinaryBaseline struct {
	ClutDataBinaryBaseline *ClutDataBinaryBaseline `protobuf:"bytes,31,opt,name=clut_data_binary_baseline,json=clutDataBinaryBaseline,proto3,oneof"`
}

type Value_StillFrameCache struct {
	StillFrameCache *StillFrameCache `protobuf:"bytes,9,opt,name=still_frame_cache,json=stillFrameCache,proto3,oneof"`
}

type Value_FrameRateStatus struct {
	FrameRateStatus *FrameRateStatus `protobuf:"bytes,41,opt,name=frame_rate_status,json=frameRateStatus,proto3,oneof"`
}

type Value_ZoomRect struct {
	ZoomRect *ZoomRect `protobuf:"bytes,45,opt,name=zoom_rect,json=zoomRect,proto3,oneof"`
}

type Value_Hsl struct {
	Hsl *Hsl `protobuf:"bytes,46,opt,name=hsl,proto3,oneof"`
}

type Value_KeyedZoomTable struct {
	KeyedZoomTable *KeyedZoomTable `protobuf:"bytes,48,opt,name=keyed_zoom_table,json=keyedZoomTable,proto3,oneof"`
}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_StringValue_2) isValue_Kind() {}

func (*Value_StringValue_7) isValue_Kind() {}

func (*Value_DeviceInfo) isValue_Kind() {}

func (*Value_WbRedBlueOffset) isValue_Kind() {}

func (*Value_Rect) isValue_Kind() {}

func (*Value_ColorStyle) isValue_Kind() {}

func (*Value_IntWrapper) isValue_Kind() {}

func (*Value_RectList) isValue_Kind() {}

func (*Value_StringWrapper) isValue_Kind() {}

func (*Value_SceneProfilePack) isValue_Kind() {}

func (*Value_Empty) isValue_Kind() {}

func (*Value_AiParameterStartStop) isValue_Kind() {}

func (*Value_RawFrameCache) isValue_Kind() {}

func (*Value_ClutDataBinaryBaseline) isValue_Kind() {}

func (*Value_StillFrameCache) isValue_Kind() {}

func (*Value_FrameRateStatus) isValue_Kind() {}

func (*Value_ZoomRect) isValue_Kind() {}

func (*Value_Hsl) isValue_Kind() {}

func (*Value_KeyedZoomTable) isValue_Kind() {}

type IntWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntWrapper) Reset() {
	*x = IntWrapper{}
	mi := &file_yolocam_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntWrapper) ProtoMessage() {}

func (x *IntWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntWrapper.ProtoReflect.Descriptor instead.
func (*IntWrapper) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *IntWrapper) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StringWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringWrapper) Reset() {
	*x = StringWrapper{}
	mi := &file_yolocam_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringWrapper) ProtoMessage() {}

func (x *StringWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringWrapper.ProtoReflect.Descriptor instead.
func (*StringWrapper) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *StringWrapper) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_yolocam_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_envelope_proto_rawDescGZIP(), []int{4}
}

var File_yolocam_v1_envelope_proto protoreflect.FileDescriptor

const file_yolocam_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x19yolocam/v1/envelope.proto\x12\n" +
	"yolocam.v1\x1a\x1byolocam/v1/ai_capture.proto\x1a\x16yolocam/v1/color.proto\x1a\x17yolocam/v1/device.proto\x1a\x1byolocam/v1/focus_zoom.proto\x1a\x19yolocam/v1/property.proto\x1a\x1ayolocam/v1/telemetry.proto\x1a\x1dyolocam/v1/whitebalance.proto\"\xbd\x01\n" +
	"\aMessage\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.yolocam.v1.MessageTypeR\x04type\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x122\n" +
	"\bproperty\x18\x05 \x01(\x0e2\x16.yolocam.v1.PropertyIdR\bproperty\x12'\n" +
	"\x05value\x18\x06 \x01(\v2\x11.yolocam.v1.ValueR\x05value\"\xcb\t\n" +
	"\x05Value\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12&\n" +
	"\x0estring_value_2\x18\x02 \x01(\tH\x00R\fstringValue2\x12&\n" +
	"\x0estring_value_7\x18\a \x01(\tH\x00R\fstringValue7\x129\n" +
	"\vdevice_info\x18\n" +
	" \x01(\v2\x16.yolocam.v1.DeviceInfoH\x00R\n" +
	"deviceInfo\x12H\n" +
	"\x12wb_red_blue_offset\x18\r \x01(\v2\x19.yolocam.v1.RedBlueOffsetH\x00R\x0fwbRedBlueOffset\x12&\n" +
	"\x04rect\x18\x0e \x01(\v2\x10.yolocam.v1.RectH\x00R\x04rect\x129\n" +
	"\vcolor_style\x18\x10 \x01(\v2\x16.yolocam.v1.ColorStyleH\x00R\n" +
	"colorStyle\x129\n" +
	"\vint_wrapper\x18\x11 \x01(\v2\x16.yolocam.v1.IntWrapperH\x00R\n" +
	"intWrapper\x123\n" +
	"\trect_list\x18\x13 \x01(\v2\x14.yolocam.v1.RectListH\x00R\brectList\x12B\n" +
	"\x0estring_wrapper\x18\x16 \x01(\v2\x19.yolocam.v1.StringWrapperH\x00R\rstringWrapper\x12K\n" +
	"\x12scene_profile_pack\x18\x05 \x01(\v2\x1b.yolocam.v1.ScenProfilePackH\x00R\x10sceneProfilePack\x12)\n" +
	"\x05empty\x18\x1c \x01(\v2\x11.yolocam.v1.EmptyH\x00R\x05empty\x12Y\n" +
	"\x17ai_parameter_start_stop\x18\x1d \x01(\v2 .yolocam.v1.AiParameterStartStopH\x00R\x14aiParameterStartStop\x12C\n" +
	"\x0fraw_frame_cache\x18\x1e \x01(\v2\x19.yolocam.v1.RawFrameCacheH\x00R\rrawFrameCache\x12_\n" +
	"\x19clut_data_binary_baseline\x18\x1f \x01(\v2\".yolocam.v1.ClutDataBinaryBaselineH\x00R\x16clutDataBinaryBaseline\x12I\n" +
	"\x11still_frame_cache\x18\t \x01(\v2\x1b.yolocam.v1.StillFrameCacheH\x00R\x0fstillFrameCache\x12I\n" +
	"\x11frame_rate_status\x18) \x01(\v2\x1b.yolocam.v1.FrameRateStatusH\x00R\x0fframeRateStatus\x123\n" +
	"\tzoom_rect\x18- \x01(\v2\x14.yolocam.v1.ZoomRectH\x00R\bzoomRect\x12#\n" +
	"\x03hsl\x18. \x01(\v2\x0f.yolocam.v1.HslH\x00R\x03hsl\x12F\n" +
	"\x10keyed_zoom_table\x180 \x01(\v2\x1a.yolocam.v1.KeyedZoomTableH\x00R\x0ekeyedZoomTableB\x06\n" +
	"\x04kind\"\"\n" +
	"\n" +
	"IntWrapper\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\"%\n" +
	"\rStringWrapper\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\a\n" +
	"\x05Empty*\x86\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MESSAGE_TYPE_GET\x10\x01\x12\x14\n" +
	"\x10MESSAGE_TYPE_SET\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_REPLY\x10\x04\x12\x15\n" +
	"\x11MESSAGE_TYPE_PUSH\x10\x05B\xaa\x01\n" +
	"\x0ecom.yolocam.v1B\rEnvelopeProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_envelope_proto_rawDescOnce sync.Once
	file_yolocam_v1_envelope_proto_rawDescData []byte
)

func file_yolocam_v1_envelope_proto_rawDescGZIP() []byte {
	file_yolocam_v1_envelope_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_envelope_proto_rawDesc), len(file_yolocam_v1_envelope_proto_rawDesc)))
	})
	return file_yolocam_v1_envelope_proto_rawDescData
}

var file_yolocam_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yolocam_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_yolocam_v1_envelope_proto_goTypes = []any{
	(MessageType)(0),               // 0: yolocam.v1.MessageType
	(*Message)(nil),                // 1: yolocam.v1.Message
	(*Value)(nil),                  // 2: yolocam.v1.Value
	(*IntWrapper)(nil),             // 3: yolocam.v1.IntWrapper
	(*StringWrapper)(nil),          // 4: yolocam.v1.StringWrapper
	(*Empty)(nil),                  // 5: yolocam.v1.Empty
	(PropertyId)(0),                // 6: yolocam.v1.PropertyId
	(*DeviceInfo)(nil),             // 7: yolocam.v1.DeviceInfo
	(*RedBlueOffset)(nil),          // 8: yolocam.v1.RedBlueOffset
	(*Rect)(nil),                   // 9: yolocam.v1.Rect
	(*ColorStyle)(nil),             // 10: yolocam.v1.ColorStyle
	(*RectList)(nil),               // 11: yolocam.v1.RectList
	(*ScenProfilePack)(nil),        // 12: yolocam.v1.ScenProfilePack
	(*AiParameterStartStop)(nil),   // 13: yolocam.v1.AiParameterStartStop
	(*RawFrameCache)(nil),          // 14: yolocam.v1.RawFrameCache
	(*ClutDataBinaryBaseline)(nil), // 15: yolocam.v1.ClutDataBinaryBaseline
	(*StillFrameCache)(nil),        // 16: yolocam.v1.StillFrameCache
	(*FrameRateStatus)(nil),        // 17: yolocam.v1.FrameRateStatus
	(*ZoomRect)(nil),               // 18: yolocam.v1.ZoomRect
	(*Hsl)(nil),                    // 19: yolocam.v1.Hsl
	(*KeyedZoomTable)(nil),         // 20: yolocam.v1.KeyedZoomTable
}
var file_yolocam_v1_envelope_proto_depIdxs = []int32{
	0,  // 0: yolocam.v1.Message.type:type_name -> yolocam.v1.MessageType
	6,  // 1: yolocam.v1.Message.property:type_name -> yolocam.v1.PropertyId
	2,  // 2: yolocam.v1.Message.value:type_name -> yolocam.v1.Value
	7,  // 3: yolocam.v1.Value.device_info:type_name -> yolocam.v1.DeviceInfo
	8,  // 4: yolocam.v1.Value.wb_red_blue_offset:type_name -> yolocam.v1.RedBlueOffset
	9,  // 5: yolocam.v1.Value.rect:type_name -> yolocam.v1.Rect
	10, // 6: yolocam.v1.Value.color_style:type_name -> yolocam.v1.ColorStyle
	3,  // 7: yolocam.v1.Value.int_wrapper:type_name -> yolocam.v1.IntWrapper
	11, // 8: yolocam.v1.Value.rect_list:type_name -> yolocam.v1.RectList
	4,  // 9: yolocam.v1.Value.string_wrapper:type_name -> yolocam.v1.StringWrapper
	12, // 10: yolocam.v1.Value.scene_profile_pack:type_name -> yolocam.v1.ScenProfilePack
	5,  // 11: yolocam.v1.Value.empty:type_name -> yolocam.v1.Empty
	13, // 12: yolocam.v1.Value.ai_parameter_start_stop:type_name -> yolocam.v1.AiParameterStartStop
	14, // 13: yolocam.v1.Value.raw_frame_cache:type_name -> yolocam.v1.RawFrameCache
	15, // 14: yolocam.v1.Value.clut_data_binary_baseline:type_name -> yolocam.v1.ClutDataBinaryBaseline
	16, // 15: yolocam.v1.Value.still_frame_cache:type_name -> yolocam.v1.StillFrameCache
	17, // 16: yolocam.v1.Value.frame_rate_status:type_name -> yolocam.v1.FrameRateStatus
	18, // 17: yolocam.v1.Value.zoom_rect:type_name -> yolocam.v1.ZoomRect
	19, // 18: yolocam.v1.Value.hsl:type_name -> yolocam.v1.Hsl
	20, // 19: yolocam.v1.Value.keyed_zoom_table:type_name -> yolocam.v1.KeyedZoomTable
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_yolocam_v1_envelope_proto_init() }
func file_yolocam_v1_envelope_proto_init() {
	if File_yolocam_v1_envelope_proto != nil {
		return
	}
	file_yolocam_v1_ai_capture_proto_init()
	file_yolocam_v1_color_proto_init()
	file_yolocam_v1_device_proto_init()
	file_yolocam_v1_focus_zoom_proto_init()
	file_yolocam_v1_property_proto_init()
	file_yolocam_v1_telemetry_proto_init()
	file_yolocam_v1_whitebalance_proto_init()
	file_yolocam_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_IntValue)(nil),
		(*Value_StringValue_2)(nil),
		(*Value_StringValue_7)(nil),
		(*Value_DeviceInfo)(nil),
		(*Value_WbRedBlueOffset)(nil),
		(*Value_Rect)(nil),
		(*Value_ColorStyle)(nil),
		(*Value_IntWrapper)(nil),
		(*Value_RectList)(nil),
		(*Value_StringWrapper)(nil),
		(*Value_SceneProfilePack)(nil),
		(*Value_Empty)(nil),
		(*Value_AiParameterStartStop)(nil),
		(*Value_RawFrameCache)(nil),
		(*Value_ClutDataBinaryBaseline)(nil),
		(*Value_StillFrameCache)(nil),
		(*Value_FrameRateStatus)(nil),
		(*Value_ZoomRect)(nil),
		(*Value_Hsl)(nil),
		(*Value_KeyedZoomTable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_envelope_proto_rawDesc), len(file_yolocam_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_envelope_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_envelope_proto_depIdxs,
		EnumInfos:         file_yolocam_v1_envelope_proto_enumTypes,
		MessageInfos:      file_yolocam_v1_envelope_proto_msgTypes,
	}.Build()
	File_yolocam_v1_envelope_proto = out.File
	file_yolocam_v1_envelope_proto_goTypes = nil
	file_yolocam_v1_envelope_proto_depIdxs = nil
}
