// Copyright 2026 Joshua Winkler and The yolocam Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/focus_zoom.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used directly by property 24 (focus_region_rect) and wrapped in RectList by property 59
// (tracking_rect_push). Coordinates are normalised 0..1.
type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_focus_zoom_proto_rawDescGZIP(), []int{0}
}

func (x *Rect) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Rect) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Rect) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Rect) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

// Empty list means Focus Type=Face detected no subject. Otherwise one Rect per tracked face.
type RectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rects         []*Rect                `protobuf:"bytes,1,rep,name=rects,proto3" json:"rects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RectList) Reset() {
	*x = RectList{}
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectList) ProtoMessage() {}

func (x *RectList) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectList.ProtoReflect.Descriptor instead.
func (*RectList) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_focus_zoom_proto_rawDescGZIP(), []int{1}
}

func (x *RectList) GetRects() []*Rect {
	if x != nil {
		return x.Rects
	}
	return nil
}

// x1/y1/x2/y2 are the Zoom > Location crop rect (normalised 0..1)
// zoom_factor is Zoom > Range (1.0..4.0)
//
// At zoom_factor=1.0 the crop covers the full frame and x1/y1 are omitted
type ZoomRect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	ZoomFactor    float32                `protobuf:"fixed32,3,opt,name=zoom_factor,json=zoomFactor,proto3" json:"zoom_factor,omitempty"`
	X2            float32                `protobuf:"fixed32,4,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,5,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoomRect) Reset() {
	*x = ZoomRect{}
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoomRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoomRect) ProtoMessage() {}

func (x *ZoomRect) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoomRect.ProtoReflect.Descriptor instead.
func (*ZoomRect) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_focus_zoom_proto_rawDescGZIP(), []int{2}
}

func (x *ZoomRect) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *ZoomRect) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *ZoomRect) GetZoomFactor() float32 {
	if x != nil {
		return x.ZoomFactor
	}
	return 0
}

func (x *ZoomRect) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *ZoomRect) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type KeyedZoomRect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // "0".."3", one per Zoom A/B/C/D preset slot
	Value         *ZoomRect              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyedZoomRect) Reset() {
	*x = KeyedZoomRect{}
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyedZoomRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedZoomRect) ProtoMessage() {}

func (x *KeyedZoomRect) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedZoomRect.ProtoReflect.Descriptor instead.
func (*KeyedZoomRect) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_focus_zoom_proto_rawDescGZIP(), []int{3}
}

func (x *KeyedZoomRect) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyedZoomRect) GetValue() *ZoomRect {
	if x != nil {
		return x.Value
	}
	return nil
}

type KeyedZoomTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*KeyedZoomTable_Entry
	//	*KeyedZoomTable_Entries_
	Payload       isKeyedZoomTable_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyedZoomTable) Reset() {
	*x = KeyedZoomTable{}
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyedZoomTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedZoomTable) ProtoMessage() {}

func (x *KeyedZoomTable) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedZoomTable.ProtoReflect.Descriptor instead.
func (*KeyedZoomTable) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_focus_zoom_proto_rawDescGZIP(), []int{4}
}

func (x *KeyedZoomTable) GetPayload() isKeyedZoomTable_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KeyedZoomTable) GetEntry() *KeyedZoomRect {
	if x != nil {
		if x, ok := x.Payload.(*KeyedZoomTable_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *KeyedZoomTable) GetEntries() *KeyedZoomTable_Entries {
	if x != nil {
		if x, ok := x.Payload.(*KeyedZoomTable_Entries_); ok {
			return x.Entries
		}
	}
	return nil
}

type isKeyedZoomTable_Payload interface {
	isKeyedZoomTable_Payload()
}

type KeyedZoomTable_Entry struct {
	Entry *KeyedZoomRect `protobuf:"bytes,1,opt,name=entry,proto3,oneof"`
}

type KeyedZoomTable_Entries_ struct {
	Entries *KeyedZoomTable_Entries `protobuf:"bytes,2,opt,name=entries,proto3,oneof"`
}

func (*KeyedZoomTable_Entry) isKeyedZoomTable_Payload() {}

func (*KeyedZoomTable_Entries_) isKeyedZoomTable_Payload() {}

type KeyedZoomTable_Entries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyedZoomRect       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyedZoomTable_Entries) Reset() {
	*x = KeyedZoomTable_Entries{}
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyedZoomTable_Entries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedZoomTable_Entries) ProtoMessage() {}

func (x *KeyedZoomTable_Entries) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_focus_zoom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedZoomTable_Entries.ProtoReflect.Descriptor instead.
func (*KeyedZoomTable_Entries) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_focus_zoom_proto_rawDescGZIP(), []int{4, 0}
}

func (x *KeyedZoomTable_Entries) GetEntries() []*KeyedZoomRect {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_yolocam_v1_focus_zoom_proto protoreflect.FileDescriptor

const file_yolocam_v1_focus_zoom_proto_rawDesc = "" +
	"\n" +
	"\x1byolocam/v1/focus_zoom.proto\x12\n" +
	"yolocam.v1\"F\n" +
	"\x04Rect\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x02R\x02y2\"2\n" +
	"\bRectList\x12&\n" +
	"\x05rects\x18\x01 \x03(\v2\x10.yolocam.v1.RectR\x05rects\"k\n" +
	"\bZoomRect\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x1f\n" +
	"\vzoom_factor\x18\x03 \x01(\x02R\n" +
	"zoomFactor\x12\x0e\n" +
	"\x02x2\x18\x04 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x05 \x01(\x02R\x02y2\"M\n" +
	"\rKeyedZoomRect\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.yolocam.v1.ZoomRectR\x05value\"\xce\x01\n" +
	"\x0eKeyedZoomTable\x121\n" +
	"\x05entry\x18\x01 \x01(\v2\x19.yolocam.v1.KeyedZoomRectH\x00R\x05entry\x12>\n" +
	"\aentries\x18\x02 \x01(\v2\".yolocam.v1.KeyedZoomTable.EntriesH\x00R\aentries\x1a>\n" +
	"\aEntries\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.yolocam.v1.KeyedZoomRectR\aentriesB\t\n" +
	"\apayloadB\xab\x01\n" +
	"\x0ecom.yolocam.v1B\x0eFocusZoomProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_focus_zoom_proto_rawDescOnce sync.Once
	file_yolocam_v1_focus_zoom_proto_rawDescData []byte
)

func file_yolocam_v1_focus_zoom_proto_rawDescGZIP() []byte {
	file_yolocam_v1_focus_zoom_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_focus_zoom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_focus_zoom_proto_rawDesc), len(file_yolocam_v1_focus_zoom_proto_rawDesc)))
	})
	return file_yolocam_v1_focus_zoom_proto_rawDescData
}

var file_yolocam_v1_focus_zoom_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_yolocam_v1_focus_zoom_proto_goTypes = []any{
	(*Rect)(nil),                   // 0: yolocam.v1.Rect
	(*RectList)(nil),               // 1: yolocam.v1.RectList
	(*ZoomRect)(nil),               // 2: yolocam.v1.ZoomRect
	(*KeyedZoomRect)(nil),          // 3: yolocam.v1.KeyedZoomRect
	(*KeyedZoomTable)(nil),         // 4: yolocam.v1.KeyedZoomTable
	(*KeyedZoomTable_Entries)(nil), // 5: yolocam.v1.KeyedZoomTable.Entries
}
var file_yolocam_v1_focus_zoom_proto_depIdxs = []int32{
	0, // 0: yolocam.v1.RectList.rects:type_name -> yolocam.v1.Rect
	2, // 1: yolocam.v1.KeyedZoomRect.value:type_name -> yolocam.v1.ZoomRect
	3, // 2: yolocam.v1.KeyedZoomTable.entry:type_name -> yolocam.v1.KeyedZoomRect
	5, // 3: yolocam.v1.KeyedZoomTable.entries:type_name -> yolocam.v1.KeyedZoomTable.Entries
	3, // 4: yolocam.v1.KeyedZoomTable.Entries.entries:type_name -> yolocam.v1.KeyedZoomRect
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_yolocam_v1_focus_zoom_proto_init() }
func file_yolocam_v1_focus_zoom_proto_init() {
	if File_yolocam_v1_focus_zoom_proto != nil {
		return
	}
	file_yolocam_v1_focus_zoom_proto_msgTypes[4].OneofWrappers = []any{
		(*KeyedZoomTable_Entry)(nil),
		(*KeyedZoomTable_Entries_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_focus_zoom_proto_rawDesc), len(file_yolocam_v1_focus_zoom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_focus_zoom_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_focus_zoom_proto_depIdxs,
		MessageInfos:      file_yolocam_v1_focus_zoom_proto_msgTypes,
	}.Build()
	File_yolocam_v1_focus_zoom_proto = out.File
	file_yolocam_v1_focus_zoom_proto_goTypes = nil
	file_yolocam_v1_focus_zoom_proto_depIdxs = nil
}
