// Copyright 2026 Joshua Winkler and The yolocam Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/property.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyId int32

const (
	PropertyId_PROPERTY_ID_UNSPECIFIED               PropertyId = 0
	PropertyId_PROPERTY_ID_DEVICE_INFO               PropertyId = 1   // inferred
	PropertyId_PROPERTY_ID_FRAME_RATE                PropertyId = 5   // confirmed
	PropertyId_PROPERTY_ID_SHARPNESS                 PropertyId = 8   // confirmed
	PropertyId_PROPERTY_ID_CONTRAST                  PropertyId = 9   // confirmed
	PropertyId_PROPERTY_ID_SATURATION                PropertyId = 10  // confirmed
	PropertyId_PROPERTY_ID_EXPOSURE_TYPE             PropertyId = 14  // confirmed
	PropertyId_PROPERTY_ID_EV                        PropertyId = 15  // confirmed
	PropertyId_PROPERTY_ID_ANTI_FLICKER              PropertyId = 16  // confirmed
	PropertyId_PROPERTY_ID_EXPOSURE_ISO              PropertyId = 17  // confirmed
	PropertyId_PROPERTY_ID_SHUTTER_US                PropertyId = 18  // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_20                PropertyId = 20  // unknown
	PropertyId_PROPERTY_ID_WB_TYPE                   PropertyId = 21  // confirmed
	PropertyId_PROPERTY_ID_WB_KELVIN                 PropertyId = 22  // confirmed
	PropertyId_PROPERTY_ID_FOCUS_TYPE                PropertyId = 23  // confirmed
	PropertyId_PROPERTY_ID_FOCUS_REGION_RECT         PropertyId = 24  // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_26                PropertyId = 26  // unknown
	PropertyId_PROPERTY_ID_VIGNETTING_CORRECTION     PropertyId = 27  // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_31                PropertyId = 31  // unknown
	PropertyId_PROPERTY_ID_WB_RED_BLUE_OFFSET        PropertyId = 33  // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_38                PropertyId = 38  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_42                PropertyId = 42  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_47                PropertyId = 47  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_48                PropertyId = 48  // unknown
	PropertyId_PROPERTY_ID_COLOR_STYLE               PropertyId = 50  // confirmed
	PropertyId_PROPERTY_ID_STYLE_BUNDLE_APPLIED_PUSH PropertyId = 51  // inferred, PUSH-only
	PropertyId_PROPERTY_ID_SCENE_PROFILE_PACK        PropertyId = 52  // confirmed
	PropertyId_PROPERTY_ID_COLOR_STYLE_ID_ECHO       PropertyId = 53  // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_58                PropertyId = 58  // unknown
	PropertyId_PROPERTY_ID_TRACKING_RECT_PUSH        PropertyId = 59  // confirmed, PUSH-only
	PropertyId_PROPERTY_ID_UNNAMED_60                PropertyId = 60  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_61                PropertyId = 61  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_62                PropertyId = 62  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_63                PropertyId = 63  // unknown, GET answers status 100 not-implemented
	PropertyId_PROPERTY_ID_UNNAMED_64                PropertyId = 64  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_65                PropertyId = 65  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_67                PropertyId = 67  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_73                PropertyId = 73  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_75                PropertyId = 75  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_76                PropertyId = 76  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_77                PropertyId = 77  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_78                PropertyId = 78  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_89                PropertyId = 89  // unknown
	PropertyId_PROPERTY_ID_UNNAMED_90                PropertyId = 90  // unknown
	PropertyId_PROPERTY_ID_AI_PARAMETER_START_STOP   PropertyId = 91  // inferred, always status 100 not-implemented
	PropertyId_PROPERTY_ID_STILL_FRAME_CACHE         PropertyId = 93  // confirmed
	PropertyId_PROPERTY_ID_CLUT_DATA_BINARY_BASELINE PropertyId = 95  // confirmed
	PropertyId_PROPERTY_ID_RAW_FRAME_CACHE           PropertyId = 100 // inferred
	PropertyId_PROPERTY_ID_DR                        PropertyId = 102 // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_103               PropertyId = 103 // unknown
	PropertyId_PROPERTY_ID_WB_AUTO_LOCK              PropertyId = 104 // confirmed
	PropertyId_PROPERTY_ID_WB_TONE                   PropertyId = 105 // confirmed
	PropertyId_PROPERTY_ID_EXPOSURE_AUTO_LOCK        PropertyId = 106 // confirmed
	PropertyId_PROPERTY_ID_BLUETOOTH_VERSION         PropertyId = 109 // confirmed
	PropertyId_PROPERTY_ID_MANUAL_FOCUS              PropertyId = 111 // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_112               PropertyId = 112 // unknown
	PropertyId_PROPERTY_ID_UNNAMED_116               PropertyId = 116 // unknown, date-coded like 109, different sub-component
	PropertyId_PROPERTY_ID_ZOOM                      PropertyId = 117 // confirmed
	PropertyId_PROPERTY_ID_HSL                       PropertyId = 118 // confirmed
	PropertyId_PROPERTY_ID_ZOOM_PRESET_SLOT          PropertyId = 127 // confirmed
	PropertyId_PROPERTY_ID_HSL_ENABLED               PropertyId = 128 // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_210               PropertyId = 210 // inferred, PUSH-only, fires on session re-arm
	PropertyId_PROPERTY_ID_ALWAYS_ON                 PropertyId = 212 // confirmed
	PropertyId_PROPERTY_ID_UNNAMED_213               PropertyId = 213 // unknown, GET answered as PUSH not REPLY
	PropertyId_PROPERTY_ID_SESSION_ATTACH            PropertyId = 215 // confirmed
)

// Enum value maps for PropertyId.
var (
	PropertyId_name = map[int32]string{
		0:   "PROPERTY_ID_UNSPECIFIED",
		1:   "PROPERTY_ID_DEVICE_INFO",
		5:   "PROPERTY_ID_FRAME_RATE",
		8:   "PROPERTY_ID_SHARPNESS",
		9:   "PROPERTY_ID_CONTRAST",
		10:  "PROPERTY_ID_SATURATION",
		14:  "PROPERTY_ID_EXPOSURE_TYPE",
		15:  "PROPERTY_ID_EV",
		16:  "PROPERTY_ID_ANTI_FLICKER",
		17:  "PROPERTY_ID_EXPOSURE_ISO",
		18:  "PROPERTY_ID_SHUTTER_US",
		20:  "PROPERTY_ID_UNNAMED_20",
		21:  "PROPERTY_ID_WB_TYPE",
		22:  "PROPERTY_ID_WB_KELVIN",
		23:  "PROPERTY_ID_FOCUS_TYPE",
		24:  "PROPERTY_ID_FOCUS_REGION_RECT",
		26:  "PROPERTY_ID_UNNAMED_26",
		27:  "PROPERTY_ID_VIGNETTING_CORRECTION",
		31:  "PROPERTY_ID_UNNAMED_31",
		33:  "PROPERTY_ID_WB_RED_BLUE_OFFSET",
		38:  "PROPERTY_ID_UNNAMED_38",
		42:  "PROPERTY_ID_UNNAMED_42",
		47:  "PROPERTY_ID_UNNAMED_47",
		48:  "PROPERTY_ID_UNNAMED_48",
		50:  "PROPERTY_ID_COLOR_STYLE",
		51:  "PROPERTY_ID_STYLE_BUNDLE_APPLIED_PUSH",
		52:  "PROPERTY_ID_SCENE_PROFILE_PACK",
		53:  "PROPERTY_ID_COLOR_STYLE_ID_ECHO",
		58:  "PROPERTY_ID_UNNAMED_58",
		59:  "PROPERTY_ID_TRACKING_RECT_PUSH",
		60:  "PROPERTY_ID_UNNAMED_60",
		61:  "PROPERTY_ID_UNNAMED_61",
		62:  "PROPERTY_ID_UNNAMED_62",
		63:  "PROPERTY_ID_UNNAMED_63",
		64:  "PROPERTY_ID_UNNAMED_64",
		65:  "PROPERTY_ID_UNNAMED_65",
		67:  "PROPERTY_ID_UNNAMED_67",
		73:  "PROPERTY_ID_UNNAMED_73",
		75:  "PROPERTY_ID_UNNAMED_75",
		76:  "PROPERTY_ID_UNNAMED_76",
		77:  "PROPERTY_ID_UNNAMED_77",
		78:  "PROPERTY_ID_UNNAMED_78",
		89:  "PROPERTY_ID_UNNAMED_89",
		90:  "PROPERTY_ID_UNNAMED_90",
		91:  "PROPERTY_ID_AI_PARAMETER_START_STOP",
		93:  "PROPERTY_ID_STILL_FRAME_CACHE",
		95:  "PROPERTY_ID_CLUT_DATA_BINARY_BASELINE",
		100: "PROPERTY_ID_RAW_FRAME_CACHE",
		102: "PROPERTY_ID_DR",
		103: "PROPERTY_ID_UNNAMED_103",
		104: "PROPERTY_ID_WB_AUTO_LOCK",
		105: "PROPERTY_ID_WB_TONE",
		106: "PROPERTY_ID_EXPOSURE_AUTO_LOCK",
		109: "PROPERTY_ID_BLUETOOTH_VERSION",
		111: "PROPERTY_ID_MANUAL_FOCUS",
		112: "PROPERTY_ID_UNNAMED_112",
		116: "PROPERTY_ID_UNNAMED_116",
		117: "PROPERTY_ID_ZOOM",
		118: "PROPERTY_ID_HSL",
		127: "PROPERTY_ID_ZOOM_PRESET_SLOT",
		128: "PROPERTY_ID_HSL_ENABLED",
		210: "PROPERTY_ID_UNNAMED_210",
		212: "PROPERTY_ID_ALWAYS_ON",
		213: "PROPERTY_ID_UNNAMED_213",
		215: "PROPERTY_ID_SESSION_ATTACH",
	}
	PropertyId_value = map[string]int32{
		"PROPERTY_ID_UNSPECIFIED":               0,
		"PROPERTY_ID_DEVICE_INFO":               1,
		"PROPERTY_ID_FRAME_RATE":                5,
		"PROPERTY_ID_SHARPNESS":                 8,
		"PROPERTY_ID_CONTRAST":                  9,
		"PROPERTY_ID_SATURATION":                10,
		"PROPERTY_ID_EXPOSURE_TYPE":             14,
		"PROPERTY_ID_EV":                        15,
		"PROPERTY_ID_ANTI_FLICKER":              16,
		"PROPERTY_ID_EXPOSURE_ISO":              17,
		"PROPERTY_ID_SHUTTER_US":                18,
		"PROPERTY_ID_UNNAMED_20":                20,
		"PROPERTY_ID_WB_TYPE":                   21,
		"PROPERTY_ID_WB_KELVIN":                 22,
		"PROPERTY_ID_FOCUS_TYPE":                23,
		"PROPERTY_ID_FOCUS_REGION_RECT":         24,
		"PROPERTY_ID_UNNAMED_26":                26,
		"PROPERTY_ID_VIGNETTING_CORRECTION":     27,
		"PROPERTY_ID_UNNAMED_31":                31,
		"PROPERTY_ID_WB_RED_BLUE_OFFSET":        33,
		"PROPERTY_ID_UNNAMED_38":                38,
		"PROPERTY_ID_UNNAMED_42":                42,
		"PROPERTY_ID_UNNAMED_47":                47,
		"PROPERTY_ID_UNNAMED_48":                48,
		"PROPERTY_ID_COLOR_STYLE":               50,
		"PROPERTY_ID_STYLE_BUNDLE_APPLIED_PUSH": 51,
		"PROPERTY_ID_SCENE_PROFILE_PACK":        52,
		"PROPERTY_ID_COLOR_STYLE_ID_ECHO":       53,
		"PROPERTY_ID_UNNAMED_58":                58,
		"PROPERTY_ID_TRACKING_RECT_PUSH":        59,
		"PROPERTY_ID_UNNAMED_60":                60,
		"PROPERTY_ID_UNNAMED_61":                61,
		"PROPERTY_ID_UNNAMED_62":                62,
		"PROPERTY_ID_UNNAMED_63":                63,
		"PROPERTY_ID_UNNAMED_64":                64,
		"PROPERTY_ID_UNNAMED_65":                65,
		"PROPERTY_ID_UNNAMED_67":                67,
		"PROPERTY_ID_UNNAMED_73":                73,
		"PROPERTY_ID_UNNAMED_75":                75,
		"PROPERTY_ID_UNNAMED_76":                76,
		"PROPERTY_ID_UNNAMED_77":                77,
		"PROPERTY_ID_UNNAMED_78":                78,
		"PROPERTY_ID_UNNAMED_89":                89,
		"PROPERTY_ID_UNNAMED_90":                90,
		"PROPERTY_ID_AI_PARAMETER_START_STOP":   91,
		"PROPERTY_ID_STILL_FRAME_CACHE":         93,
		"PROPERTY_ID_CLUT_DATA_BINARY_BASELINE": 95,
		"PROPERTY_ID_RAW_FRAME_CACHE":           100,
		"PROPERTY_ID_DR":                        102,
		"PROPERTY_ID_UNNAMED_103":               103,
		"PROPERTY_ID_WB_AUTO_LOCK":              104,
		"PROPERTY_ID_WB_TONE":                   105,
		"PROPERTY_ID_EXPOSURE_AUTO_LOCK":        106,
		"PROPERTY_ID_BLUETOOTH_VERSION":         109,
		"PROPERTY_ID_MANUAL_FOCUS":              111,
		"PROPERTY_ID_UNNAMED_112":               112,
		"PROPERTY_ID_UNNAMED_116":               116,
		"PROPERTY_ID_ZOOM":                      117,
		"PROPERTY_ID_HSL":                       118,
		"PROPERTY_ID_ZOOM_PRESET_SLOT":          127,
		"PROPERTY_ID_HSL_ENABLED":               128,
		"PROPERTY_ID_UNNAMED_210":               210,
		"PROPERTY_ID_ALWAYS_ON":                 212,
		"PROPERTY_ID_UNNAMED_213":               213,
		"PROPERTY_ID_SESSION_ATTACH":            215,
	}
)

func (x PropertyId) Enum() *PropertyId {
	p := new(PropertyId)
	*p = x
	return p
}

func (x PropertyId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyId) Descriptor() protoreflect.EnumDescriptor {
	return file_yolocam_v1_property_proto_enumTypes[0].Descriptor()
}

func (PropertyId) Type() protoreflect.EnumType {
	return &file_yolocam_v1_property_proto_enumTypes[0]
}

func (x PropertyId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyId.Descriptor instead.
func (PropertyId) EnumDescriptor() ([]byte, []int) {
	return file_yolocam_v1_property_proto_rawDescGZIP(), []int{0}
}

var File_yolocam_v1_property_proto protoreflect.FileDescriptor

const file_yolocam_v1_property_proto_rawDesc = "" +
	"\n" +
	"\x19yolocam/v1/property.proto\x12\n" +
	"yolocam.v1*\x9c\x0f\n" +
	"\n" +
	"PropertyId\x12\x1b\n" +
	"\x17PROPERTY_ID_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROPERTY_ID_DEVICE_INFO\x10\x01\x12\x1a\n" +
	"\x16PROPERTY_ID_FRAME_RATE\x10\x05\x12\x19\n" +
	"\x15PROPERTY_ID_SHARPNESS\x10\b\x12\x18\n" +
	"\x14PROPERTY_ID_CONTRAST\x10\t\x12\x1a\n" +
	"\x16PROPERTY_ID_SATURATION\x10\n" +
	"\x12\x1d\n" +
	"\x19PROPERTY_ID_EXPOSURE_TYPE\x10\x0e\x12\x12\n" +
	"\x0ePROPERTY_ID_EV\x10\x0f\x12\x1c\n" +
	"\x18PROPERTY_ID_ANTI_FLICKER\x10\x10\x12\x1c\n" +
	"\x18PROPERTY_ID_EXPOSURE_ISO\x10\x11\x12\x1a\n" +
	"\x16PROPERTY_ID_SHUTTER_US\x10\x12\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_20\x10\x14\x12\x17\n" +
	"\x13PROPERTY_ID_WB_TYPE\x10\x15\x12\x19\n" +
	"\x15PROPERTY_ID_WB_KELVIN\x10\x16\x12\x1a\n" +
	"\x16PROPERTY_ID_FOCUS_TYPE\x10\x17\x12!\n" +
	"\x1dPROPERTY_ID_FOCUS_REGION_RECT\x10\x18\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_26\x10\x1a\x12%\n" +
	"!PROPERTY_ID_VIGNETTING_CORRECTION\x10\x1b\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_31\x10\x1f\x12\"\n" +
	"\x1ePROPERTY_ID_WB_RED_BLUE_OFFSET\x10!\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_38\x10&\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_42\x10*\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_47\x10/\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_48\x100\x12\x1b\n" +
	"\x17PROPERTY_ID_COLOR_STYLE\x102\x12)\n" +
	"%PROPERTY_ID_STYLE_BUNDLE_APPLIED_PUSH\x103\x12\"\n" +
	"\x1ePROPERTY_ID_SCENE_PROFILE_PACK\x104\x12#\n" +
	"\x1fPROPERTY_ID_COLOR_STYLE_ID_ECHO\x105\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_58\x10:\x12\"\n" +
	"\x1ePROPERTY_ID_TRACKING_RECT_PUSH\x10;\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_60\x10<\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_61\x10=\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_62\x10>\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_63\x10?\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_64\x10@\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_65\x10A\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_67\x10C\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_73\x10I\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_75\x10K\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_76\x10L\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_77\x10M\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_78\x10N\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_89\x10Y\x12\x1a\n" +
	"\x16PROPERTY_ID_UNNAMED_90\x10Z\x12'\n" +
	"#PROPERTY_ID_AI_PARAMETER_START_STOP\x10[\x12!\n" +
	"\x1dPROPERTY_ID_STILL_FRAME_CACHE\x10]\x12)\n" +
	"%PROPERTY_ID_CLUT_DATA_BINARY_BASELINE\x10_\x12\x1f\n" +
	"\x1bPROPERTY_ID_RAW_FRAME_CACHE\x10d\x12\x12\n" +
	"\x0ePROPERTY_ID_DR\x10f\x12\x1b\n" +
	"\x17PROPERTY_ID_UNNAMED_103\x10g\x12\x1c\n" +
	"\x18PROPERTY_ID_WB_AUTO_LOCK\x10h\x12\x17\n" +
	"\x13PROPERTY_ID_WB_TONE\x10i\x12\"\n" +
	"\x1ePROPERTY_ID_EXPOSURE_AUTO_LOCK\x10j\x12!\n" +
	"\x1dPROPERTY_ID_BLUETOOTH_VERSION\x10m\x12\x1c\n" +
	"\x18PROPERTY_ID_MANUAL_FOCUS\x10o\x12\x1b\n" +
	"\x17PROPERTY_ID_UNNAMED_112\x10p\x12\x1b\n" +
	"\x17PROPERTY_ID_UNNAMED_116\x10t\x12\x14\n" +
	"\x10PROPERTY_ID_ZOOM\x10u\x12\x13\n" +
	"\x0fPROPERTY_ID_HSL\x10v\x12 \n" +
	"\x1cPROPERTY_ID_ZOOM_PRESET_SLOT\x10\x7f\x12\x1c\n" +
	"\x17PROPERTY_ID_HSL_ENABLED\x10\x80\x01\x12\x1c\n" +
	"\x17PROPERTY_ID_UNNAMED_210\x10\xd2\x01\x12\x1a\n" +
	"\x15PROPERTY_ID_ALWAYS_ON\x10\xd4\x01\x12\x1c\n" +
	"\x17PROPERTY_ID_UNNAMED_213\x10\xd5\x01\x12\x1f\n" +
	"\x1aPROPERTY_ID_SESSION_ATTACH\x10\xd7\x01B\xaa\x01\n" +
	"\x0ecom.yolocam.v1B\rPropertyProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_property_proto_rawDescOnce sync.Once
	file_yolocam_v1_property_proto_rawDescData []byte
)

func file_yolocam_v1_property_proto_rawDescGZIP() []byte {
	file_yolocam_v1_property_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_property_proto_rawDesc), len(file_yolocam_v1_property_proto_rawDesc)))
	})
	return file_yolocam_v1_property_proto_rawDescData
}

var file_yolocam_v1_property_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yolocam_v1_property_proto_goTypes = []any{
	(PropertyId)(0), // 0: yolocam.v1.PropertyId
}
var file_yolocam_v1_property_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolocam_v1_property_proto_init() }
func file_yolocam_v1_property_proto_init() {
	if File_yolocam_v1_property_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_property_proto_rawDesc), len(file_yolocam_v1_property_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_property_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_property_proto_depIdxs,
		EnumInfos:         file_yolocam_v1_property_proto_enumTypes,
	}.Build()
	File_yolocam_v1_property_proto = out.File
	file_yolocam_v1_property_proto_goTypes = nil
	file_yolocam_v1_property_proto_depIdxs = nil
}
