// Copyright 2026 Joshua Winkler and The yolocam Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/telemetry.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PUSH tied to session re-arm (SET 215=1) in general. A frame_rate change is just
// one path that triggers a re-arm. frame_rate mirrors the current frame rate exactly when this
// fires alongside a frame_rate change.
//
// unknown_1 and unknown_3 have held constant (2 and 1) across every observation.
type FrameRateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1     uint32                 `protobuf:"varint,1,opt,name=unknown_1,json=unknown1,proto3" json:"unknown_1,omitempty"`
	FrameRate     uint32                 `protobuf:"varint,2,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	Unknown_3     uint32                 `protobuf:"varint,3,opt,name=unknown_3,json=unknown3,proto3" json:"unknown_3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRateStatus) Reset() {
	*x = FrameRateStatus{}
	mi := &file_yolocam_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRateStatus) ProtoMessage() {}

func (x *FrameRateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRateStatus.ProtoReflect.Descriptor instead.
func (*FrameRateStatus) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRateStatus) GetUnknown_1() uint32 {
	if x != nil {
		return x.Unknown_1
	}
	return 0
}

func (x *FrameRateStatus) GetFrameRate() uint32 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

func (x *FrameRateStatus) GetUnknown_3() uint32 {
	if x != nil {
		return x.Unknown_3
	}
	return 0
}

var File_yolocam_v1_telemetry_proto protoreflect.FileDescriptor

const file_yolocam_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ayolocam/v1/telemetry.proto\x12\n" +
	"yolocam.v1\"j\n" +
	"\x0fFrameRateStatus\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\rR\bunknown1\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x02 \x01(\rR\tframeRate\x12\x1b\n" +
	"\tunknown_3\x18\x03 \x01(\rR\bunknown3B\xab\x01\n" +
	"\x0ecom.yolocam.v1B\x0eTelemetryProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_telemetry_proto_rawDescOnce sync.Once
	file_yolocam_v1_telemetry_proto_rawDescData []byte
)

func file_yolocam_v1_telemetry_proto_rawDescGZIP() []byte {
	file_yolocam_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_telemetry_proto_rawDesc), len(file_yolocam_v1_telemetry_proto_rawDesc)))
	})
	return file_yolocam_v1_telemetry_proto_rawDescData
}

var file_yolocam_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yolocam_v1_telemetry_proto_goTypes = []any{
	(*FrameRateStatus)(nil), // 0: yolocam.v1.FrameRateStatus
}
var file_yolocam_v1_telemetry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolocam_v1_telemetry_proto_init() }
func file_yolocam_v1_telemetry_proto_init() {
	if File_yolocam_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_telemetry_proto_rawDesc), len(file_yolocam_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_yolocam_v1_telemetry_proto_msgTypes,
	}.Build()
	File_yolocam_v1_telemetry_proto = out.File
	file_yolocam_v1_telemetry_proto_goTypes = nil
	file_yolocam_v1_telemetry_proto_depIdxs = nil
}
