// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yolocam/v1/whitebalance.proto

package yolocamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedBlueOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedOffset     uint32                 `protobuf:"varint,1,opt,name=red_offset,json=redOffset,proto3" json:"red_offset,omitempty"`
	BlueOffset    uint32                 `protobuf:"varint,2,opt,name=blue_offset,json=blueOffset,proto3" json:"blue_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedBlueOffset) Reset() {
	*x = RedBlueOffset{}
	mi := &file_yolocam_v1_whitebalance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedBlueOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedBlueOffset) ProtoMessage() {}

func (x *RedBlueOffset) ProtoReflect() protoreflect.Message {
	mi := &file_yolocam_v1_whitebalance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedBlueOffset.ProtoReflect.Descriptor instead.
func (*RedBlueOffset) Descriptor() ([]byte, []int) {
	return file_yolocam_v1_whitebalance_proto_rawDescGZIP(), []int{0}
}

func (x *RedBlueOffset) GetRedOffset() uint32 {
	if x != nil {
		return x.RedOffset
	}
	return 0
}

func (x *RedBlueOffset) GetBlueOffset() uint32 {
	if x != nil {
		return x.BlueOffset
	}
	return 0
}

var File_yolocam_v1_whitebalance_proto protoreflect.FileDescriptor

const file_yolocam_v1_whitebalance_proto_rawDesc = "" +
	"\n" +
	"\x1dyolocam/v1/whitebalance.proto\x12\n" +
	"yolocam.v1\"O\n" +
	"\rRedBlueOffset\x12\x1d\n" +
	"\n" +
	"red_offset\x18\x01 \x01(\rR\tredOffset\x12\x1f\n" +
	"\vblue_offset\x18\x02 \x01(\rR\n" +
	"blueOffsetB\xae\x01\n" +
	"\x0ecom.yolocam.v1B\x11WhitebalanceProtoP\x01Z@github.com/bemoty/yolocam/internal/genproto/yolocam/v1;yolocamv1\xa2\x02\x03YXX\xaa\x02\n" +
	"Yolocam.V1\xca\x02\n" +
	"Yolocam\\V1\xe2\x02\x16Yolocam\\V1\\GPBMetadata\xea\x02\vYolocam::V1b\x06proto3"

var (
	file_yolocam_v1_whitebalance_proto_rawDescOnce sync.Once
	file_yolocam_v1_whitebalance_proto_rawDescData []byte
)

func file_yolocam_v1_whitebalance_proto_rawDescGZIP() []byte {
	file_yolocam_v1_whitebalance_proto_rawDescOnce.Do(func() {
		file_yolocam_v1_whitebalance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yolocam_v1_whitebalance_proto_rawDesc), len(file_yolocam_v1_whitebalance_proto_rawDesc)))
	})
	return file_yolocam_v1_whitebalance_proto_rawDescData
}

var file_yolocam_v1_whitebalance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yolocam_v1_whitebalance_proto_goTypes = []any{
	(*RedBlueOffset)(nil), // 0: yolocam.v1.RedBlueOffset
}
var file_yolocam_v1_whitebalance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yolocam_v1_whitebalance_proto_init() }
func file_yolocam_v1_whitebalance_proto_init() {
	if File_yolocam_v1_whitebalance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yolocam_v1_whitebalance_proto_rawDesc), len(file_yolocam_v1_whitebalance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yolocam_v1_whitebalance_proto_goTypes,
		DependencyIndexes: file_yolocam_v1_whitebalance_proto_depIdxs,
		MessageInfos:      file_yolocam_v1_whitebalance_proto_msgTypes,
	}.Build()
	File_yolocam_v1_whitebalance_proto = out.File
	file_yolocam_v1_whitebalance_proto_goTypes = nil
	file_yolocam_v1_whitebalance_proto_depIdxs = nil
}
